# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
- repo: self

parameters:
  - name: version
    displayName: Version
    type: string
    default: v1.0.0


trigger: none

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e9f1b348-10e7-4f61-8413-ca458fabb386'
  imageRepository: 'muratcabukdotnetdocker'
  containerRegistry: 'swarmtest.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/aspnet/3.1/nanoserver-1809/amd64/Dockerfile'
  tag: '$(Build.BuildId)'
  version: ${{ parameters.version }}
  
  # Agent VM image name
  vmImageName: 'windows-2019'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:  
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            git checkout $(version)
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
            $(version)
